import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
export default function XPProgress({ xp, progressColorClass }) {
    return (_jsxs("div", { className: "bg-white dark:bg-surface-dark rounded-2xl p-6 sm:p-8 mb-8 shadow-lg", children: [_jsxs("div", { className: "flex items-center justify-between mb-4", children: [_jsx("h2", { className: "text-xl sm:text-2xl font-bold text-text-light dark:text-text-dark", children: "XP Progress" }), _jsxs("div", { className: "text-right", children: [_jsxs("div", { className: "text-lg sm:text-xl font-semibold text-text-light dark:text-text-dark", children: [xp.currentXP.toLocaleString(), " / ", xp.totalXPForNextLevel.toLocaleString(), " XP"] }), _jsxs("div", { className: "text-sm text-text-light/70 dark:text-text-dark/70", children: [Math.round(xp.progressPercentage), "% to next level"] })] })] }), _jsxs("div", { className: "relative mb-6", children: [_jsx("div", { className: "w-full bg-gray-200 dark:bg-gray-700 rounded-full h-4 overflow-hidden", children: _jsx("div", { className: `h-full bg-gradient-to-r ${progressColorClass} rounded-full transition-all duration-1000 ease-out shadow-sm`, style: { width: `${xp.progressPercentage}%` }, children: _jsx("div", { className: "h-full bg-white/20 animate-pulse" }) }) }), _jsx("div", { className: "absolute top-0 right-0 transform translate-x-1/2 -translate-y-1/2", style: { left: `${xp.progressPercentage}%` }, children: _jsx("div", { className: "w-6 h-6 bg-white dark:bg-gray-800 rounded-full shadow-lg border-2 border-primary-500" }) })] }), _jsx("div", { className: "grid grid-cols-1 sm:grid-cols-3 gap-4", children: Object.entries(xp.xpBreakdown).map(([tier, data]) => {
                    const colors = {
                        beginner: "green",
                        intermediate: "blue",
                        expert: "purple",
                    };
                    const color = colors[tier];
                    return (_jsx("div", { className: `bg-${color}-50 dark:bg-${color}-900/20 rounded-xl p-4 border border-${color}-200 dark:border-${color}-800`, children: _jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { children: [_jsx("div", { className: `text-sm font-medium text-${color}-700 dark:text-${color}-300`, children: tier.charAt(0).toUpperCase() + tier.slice(1) }), _jsxs("div", { className: `text-lg font-bold text-${color}-800 dark:text-${color}-200`, children: ["+", data.totalXP, " XP"] })] }), _jsxs("div", { className: `text-${color}-600 dark:text-${color}-400 text-right`, children: [_jsxs("div", { className: "text-xs", children: ["+", data.xpPerWord, " XP per word"] }), _jsxs("div", { className: "text-sm font-medium", children: [data.wordsCompleted, " words"] })] })] }) }, tier));
                }) })] }));
}
