/**
 * Generate a SQL migration from a reviewed translation CSV.
 *
 * Usage:
 *   npx tsx scripts/generate-translations-migration.ts --lang th
 *
 * Reads:  src/data/translations/<lang>_review.csv
 * Writes: supabase/migrations/<timestamp>_translations_<lang>.sql
 *
 * Fails if any row still has flagged=true — fix those before running.
 */

import { readFileSync, writeFileSync } from 'fs';
import { join } from 'path';
import Papa from 'papaparse';

// ─── Args ─────────────────────────────────────────────────────────────────────

const SUPPORTED = ['th', 'zh', 'vi'];

const langArg = process.argv.find((a) => a.startsWith('--lang='))?.split('=')[1]
  ?? process.argv[process.argv.indexOf('--lang') + 1];

if (!langArg || !SUPPORTED.includes(langArg)) {
  console.error(`Usage: npx tsx scripts/generate-translations-migration.ts --lang <th|zh|vi>`);
  process.exit(1);
}

const lang = langArg;

// ─── Read CSV ─────────────────────────────────────────────────────────────────

const csvPath = join('src/data/translations', `${lang}_review.csv`);
const content = readFileSync(csvPath, 'utf-8');

type ReviewRow = {
  flashcard_id: string;
  english_text: string;
  category: string;
  native_text: string;
  flagged: string; // 'true' | 'false'
};

const result = Papa.parse<ReviewRow>(content, {
  header: true,
  skipEmptyLines: true,
});

if (result.errors.length > 0) {
  console.error('CSV parse errors:', result.errors);
  process.exit(1);
}

const rows = result.data;

// ─── Guard: no unflagged rows ─────────────────────────────────────────────────

const flagged = rows.filter((r) => r.flagged === 'true');
if (flagged.length > 0) {
  console.error(`❌ ${flagged.length} row(s) still have flagged=true in ${csvPath}`);
  console.error('Edit native_text and set flagged=false for each of these rows before generating the migration:');
  flagged.forEach((r) => console.error(`  - ${r.flashcard_id} "${r.english_text}" → "${r.native_text}"`));
  process.exit(1);
}

if (rows.length === 0) {
  console.error('No rows found in CSV.');
  process.exit(1);
}

// ─── Build SQL ────────────────────────────────────────────────────────────────

const sqlLiteral = (s: string | null): string =>
  s == null ? 'NULL' : `'${s.replace(/'/g, "''")}'`;

const timestamp = new Date()
  .toISOString()
  .replace(/[-T:.Z]/g, '')
  .slice(0, 14);

const outputPath = join('supabase/migrations', `${timestamp}_translations_${lang}.sql`);

const valueLines = rows.map(
  (r) =>
    `  (${sqlLiteral(r.flashcard_id)}, ${sqlLiteral(lang)}, ${sqlLiteral(r.native_text)}, 'human', true)`,
);

const sql = [
  `-- Generated by scripts/generate-translations-migration.ts — DO NOT EDIT BY HAND`,
  `-- Source: src/data/translations/${lang}_review.csv`,
  `-- Regenerate: review CSV → npx tsx scripts/generate-translations-migration.ts --lang ${lang}`,
  '',
  `INSERT INTO flashcard_translations (flashcard_id, language_code, native_text, source, is_reviewed)`,
  `VALUES`,
  valueLines.join(',\n'),
  `ON CONFLICT (flashcard_id, language_code) DO UPDATE`,
  `  SET native_text  = EXCLUDED.native_text,`,
  `      source       = EXCLUDED.source,`,
  `      is_reviewed  = true,`,
  `      updated_at   = now();`,
  '',
].join('\n');

writeFileSync(outputPath, sql, 'utf-8');

console.log(`✓ Wrote ${rows.length} translations to ${outputPath}`);
console.log(`  Apply with: npx supabase db push`);
