import { readFileSync, writeFileSync, readdirSync } from 'fs';
import { join } from 'path';
import { SET_META } from '../src/data/seed/sets/meta.js';
import { parseCsv } from './lib/csv-parser.js';
import {
  normalizeText,
  normalizeCategory,
  sha256SetId,
  sha256CardId,
  sqlLiteral,
} from './lib/seed-utils.js';
import { validateMeta, validateRows } from './lib/validator.js';

const CSV_DIR = 'src/data/seed/sets';
const OUTPUT = 'supabase/migrations/20260322000001_seed_csv_sets.sql';

// --- Validation ---
const csvFiles = readdirSync(CSV_DIR).filter((f) => f.endsWith('.csv'));
validateMeta(SET_META, csvFiles);

// --- Process sets in sort_order ---
const entries = Object.entries(SET_META).sort(([, a], [, b]) => a.sort_order - b.sort_order);

const lines: string[] = [
  '-- Generated by scripts/generate-seed-migration.ts — DO NOT EDIT BY HAND',
  '-- Regenerate with: npx tsx scripts/generate-seed-migration.ts',
  '-- Idempotency: ON CONFLICT (id) DO NOTHING — content changes need a new migration',
  '-- Spec: docs/superpowers/specs/2026-03-22-seed-migration-design.md',
  '',
];

let totalCards = 0;
let legacyAdapted = 0;

for (const [filename, meta] of entries) {
  const content = readFileSync(join(CSV_DIR, filename), 'utf-8');
  const rawRows = parseCsv(content, filename);

  // Normalize all text fields
  const rows = rawRows.map((row) => {
    const englishText = normalizeText(row.english_text);
    const nativeText = normalizeText(row.native_text) ?? englishText; // NOT NULL fallback
    return {
      native_text:        nativeText,
      english_text:       englishText,
      category:           normalizeCategory(row.category),
      part_of_speech:     normalizeText(row.part_of_speech),
      level:              normalizeText(row.level),
      example_sentence:   normalizeText(row.example_sentence),
      english_audio_url:  normalizeText(row.english_audio_url),
      native_audio_url:   normalizeText(row.native_audio_url),
      image_url:          normalizeText(row.image_url),
      sort_order:         row.sort_order,
    };
  });

  validateRows(rows, filename);

  // Track legacy files (native_text === english_text and no part_of_speech)
  const isLegacy = rawRows.some((r) => r.native_text === r.english_text && r.part_of_speech === null);
  if (isLegacy) legacyAdapted++;

  const setId = sha256SetId(filename);
  const isPublic = meta.is_public ?? true;

  lines.push(`-- === ${meta.title} (${filename}) ===`);
  lines.push('');
  lines.push(`INSERT INTO flashcard_sets (id, title, description, is_public, created_by)`);
  lines.push(`VALUES (${sqlLiteral(setId)}, ${sqlLiteral(meta.title)}, ${sqlLiteral(meta.description)}, ${isPublic}, null)`);
  lines.push(`ON CONFLICT (id) DO NOTHING;`);
  lines.push('');
  lines.push(`INSERT INTO flashcards (`);
  lines.push(`  id, set_id, native_text, english_text, category,`);
  lines.push(`  part_of_speech, level, example_sentence,`);
  lines.push(`  english_audio_url, native_audio_url, image_url, sort_order`);
  lines.push(`) VALUES`);

  const valueLines = rows.map((row) => {
    const cardId = sha256CardId(filename, row.english_text!, row.category, row.sort_order);
    return [
      `  (`,
      `    ${sqlLiteral(cardId)}, ${sqlLiteral(setId)},`,
      `    ${sqlLiteral(row.native_text)}, ${sqlLiteral(row.english_text)}, ${sqlLiteral(row.category)},`,
      `    ${sqlLiteral(row.part_of_speech)}, ${sqlLiteral(row.level)}, ${sqlLiteral(row.example_sentence)},`,
      `    ${sqlLiteral(row.english_audio_url)}, ${sqlLiteral(row.native_audio_url)}, ${sqlLiteral(row.image_url)}, ${row.sort_order}`,
      `  )`,
    ].join('\n');
  });

  lines.push(valueLines.join(',\n'));
  lines.push(`ON CONFLICT (id) DO NOTHING;`);
  lines.push('');

  totalCards += rows.length;
}

// --- Write output ---
writeFileSync(OUTPUT, lines.join('\n'), 'utf-8');

console.log(`${entries.length} sets, ${totalCards} cards, ${legacyAdapted} legacy file${legacyAdapted !== 1 ? 's' : ''} adapted`);
console.log(`Written to ${OUTPUT}`);
