-- supabase/migrations/20260510000002_ai_tutor_audio_bucket.sql
-- Public bucket for pre-generated AI tutor audio (opening lines, task
-- next-lines, phrasebook phrases). Generated by the author-time script
-- and served as static MP3/OGG to the client.

INSERT INTO storage.buckets (id, name, public)
VALUES ('ai-tutor-audio', 'ai-tutor-audio', true)
ON CONFLICT (id) DO NOTHING;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'storage'
      AND tablename = 'objects'
      AND policyname = 'ai_tutor_audio_public_read'
  ) THEN
    CREATE POLICY "ai_tutor_audio_public_read" ON storage.objects
      FOR SELECT USING (bucket_id = 'ai-tutor-audio');
  END IF;
END $$;
-- No insert/update/delete policies. Only the service role (script) writes.
