-- supabase/migrations/20260502000002_lesson_images_bucket.sql
-- Public bucket for lesson illustrations (vocab thumbnails, dialogue scenes,
-- exercise images, section headers, unit hero art). Generated by the
-- author-time script scripts/generate-lesson-images.ts.

INSERT INTO storage.buckets (id, name, public)
VALUES ('lesson-images', 'lesson-images', true)
ON CONFLICT (id) DO NOTHING;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'storage'
      AND tablename = 'objects'
      AND policyname = 'lesson_images_public_read'
  ) THEN
    CREATE POLICY "lesson_images_public_read" ON storage.objects
      FOR SELECT USING (bucket_id = 'lesson-images');
  END IF;
END $$;
-- No insert/update/delete policies. Only the service role (script) writes.
